version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "3000:3000"

networks:
  app-network: